#!/bin/bash
#mahavpn
#goodboy
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
OWNER=mahavpn-mantap
clear
mkdir /root/.hay
wget -P /root/.hay "https://raw.githubusercontent.com/GboyGud/clash_for_android/main/assets/hayo"
chmod +x /root/.hay/hayo
cp /root/.hay/hayo /usr/bin/boy
chmod 777 /usr/bin/boy
rm -r /root/.hay
clear
read -p "Ketik (boy) untuk masuk ke monitor, masukkan password  : " RUN
if [ $RUN = $OWNER ]; then
clear
echo -e "${green}Autentikasi SAH${NC}"
else
clear
echo -e "${red}Permintaan Ditolak, masukkan password yang benar!${NC}";
echo "Harap hubungi admin MahaVPN"
rm /usr/bin/boy
exit
fi
clear
rm /root/vnstat
rm /root/bw
boy
