#!/bin/bash
#mahavpn
#goodboy
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
OWNER=mahavpn-mantap
clear
wget -P /root "https://raw.githubusercontent.com/GboyGud/clash_for_android/main/assets/hayo"
chmod +x /root/hayo
cp /root/hayo /usr/bin/boy
chmod +x /usr/bin/boy
rm /root/hayo
clear
read -p "Ketik (boy) untuk masuk ke monitor, masukkan password  : " RUN
if [ $RUN = $OWNER ]; then
clear
echo -e "${green}Autentikasi SAH${NC}"
rm /root/stat
rm /root/monitor
else
clear
echo -e "${red}Permintaan Ditolak, masukkan password yang benar!${NC}";
echo "Harap hubungi admin MahaVPN"
rm /usr/bin/boy
rm /root/stat
rm /root/monitor
exit
fi
clear
boy
